---
- hosts: localhost
  connection: local
  vars_files:
    - vars.yml
    - versions.yml
    - vault.yml
    - env.yml
  tasks:
    - import_tasks: "./tasks/ssh.yml"
    - import_tasks: "./tasks/packages.yml"
    - import_tasks: "./tasks/git.yml"
    - import_tasks: "./tasks/dev-repos.yml"
    - import_tasks: "./tasks/docker.yml"
    - import_tasks: "./tasks/samba.yml"
    - import_tasks: "./tasks/ruby.yml"
    - import_tasks: "./tasks/php.yml"
    - import_tasks: "./tasks/composer.yml"
    - import_tasks: "./tasks/node.yml"
    - import_tasks: "./tasks/mysql.yml"
    - import_tasks: "./tasks/postgres.yml"
