---
- hosts: localhost
  connection: local
  vars_files:
    - vars.yml
    - versions.yml
    - vault.yml
    - env.yml
  tasks:
    - import_tasks: "./tasks/ssh.yml"
    - import_tasks: "./tasks/packages.yml"
    - import_tasks: "./tasks/git.yml"
    - import_tasks: "./tasks/dev-repos.yml"
    - import_tasks: "./tasks/docker.yml"
    - import_tasks: "./tasks/samba.yml"
    - import_tasks: "./tasks/ruby.yml"
    - import_tasks: "./tasks/php.yml"
    - import_tasks: "./tasks/composer.yml"
    - import_tasks: "./tasks/node.yml"
    - import_tasks: "./tasks/nvm.yml"
    - import_tasks: "./tasks/dotnet.yml"
    - import_tasks: "./tasks/mysql.yml"
    - import_tasks: "./tasks/postgres.yml"
    - import_tasks: "./tasks/mongo.yml"
    #region Redis
    - name: Check for redis config
      stat:
        path: /etc/redis/redis.conf
      register: redis_conf
    - import_tasks: ./tasks/redis.yml
      when: not redis_conf.stat.exists
    #endregion Redis
    - import_tasks: "./tasks/open-services.yml"
