---
- hosts: localhost
  connection: local
  vars_files:
    - vars.yml
    - versions.yml
    - vault.yml
    - env.yml
  tasks:
    - name: Set timezone to CST
      become: true
      timezone:
        name: America/Chicago
      tags:
        - core
    - name: Increase inotify watches
      become: true
      sysctl:
        name: fs.inotify.max_user_watches
        value: "524288"
        reload: yes
      tags:
        - inotify
        - core
    - import_tasks: "./tasks/ssh.yml"
      tags:
        - core
    - import_tasks: "./tasks/mod-motd.yml"
      become: true
      tags:
        - core
        - motd
    - import_tasks: "./tasks/packages.yml"
      tags:
        - core
    - import_tasks: "./tasks/visudo.yml"
      tags:
        - core
    - import_tasks: "./tasks/git.yml"
      tags:
        - git
        - core
    - import_tasks: "./tasks/dev-repos.yml"
      tags:
        - core
        - git
    - import_tasks: "./tasks/docker.yml"
      tags:
        - docker
    - import_tasks: "./tasks/samba.yml"
      tags:
        - samba
    - import_tasks: "./tasks/ruby.yml"
      tags:
        - ruby
    - import_tasks: "./tasks/php.yml"
      tags:
        - php
    - import_tasks: "./tasks/composer.yml"
      tags:
        - php
        - composer
    - import_tasks: "./tasks/wordpress.yml"
      tags:
        - php
        - wordpress
    # Symfony CLI is not needed
    # - import_tasks: "./tasks/symfony.yml"
    #   tags:
    #     - php
    #     - symfony
    - import_tasks: "./tasks/node.yml"
      tags:
        - node
    - import_tasks: "./tasks/nvm.yml"
      tags:
        - node
        - nvm
    - import_tasks: "./tasks/dotnet.yml"
      tags:
        - dotnet
    # Not available for Ubuntu 20.04 yet
    - import_tasks: "./tasks/powershell.yml"
      tags:
        - powershell
    - import_tasks: "./tasks/go.yml"
      tags:
        - go
    - import_tasks: "./tasks/mysql.yml"
      tags:
        - db
        - mysql
    - import_tasks: "./tasks/postgres.yml"
      tags:
        - db
        - postgres
    # Not available for Ubuntu 20.04 yet
    - import_tasks: "./tasks/mongo.yml"
      tags:
        - db
        - mongo
    #region Redis
    - name: Check for redis config
      stat:
        path: /etc/redis/redis.conf
      register: redis_conf
      tags:
        - db
        - redis
    - import_tasks: ./tasks/redis.yml
      when: not redis_conf.stat.exists
      tags:
        - db
        - redis
    #endregion Redis
    - import_tasks: "./tasks/open-services.yml"
      tags:
        - open
