---
- name: Download go
  get_url:
    url: "https://dl.google.com/go/go{{ go_version }}.linux-amd64.tar.gz"
    dest: /tmp/go.tar.gz
- name: Unpack go
  become: true
  unarchive:
    src: /tmp/go.tar.gz
    dest: /usr/local
    remote_src: yes
- name: Add go to path
  blockinfile:
    path: ~/.bashrc
    insertbefore: If not running interactively
    marker: "# {mark} ANSIBLE MANAGED GO SETUP"
    block: |
      export GOROOT="/usr/local/go"
      export PATH="$PATH:$GOROOT/bin"
      export GOPATH="$HOME/.go"
