---
- name: Open redis up for remote connections
  become: true
  lineinfile:
    path: /etc/redis/redis.conf
    regexp: "^bind"
    line: bind 0.0.0.0
  tags:
    - redis

- name: Restart redis service
  become: true
  systemd:
    name: redis
    state: restarted
  tags:
    - redis

- name: Open mongodb up for remote connections
  become: true
  lineinfile:
    path: /etc/mongod.conf
    regexp: "^  bindIp"
    line: "  bindIp: 0.0.0.0"
  tags:
    - mongo

- name: Restart mongodb service
  become: true
  service:
    name: mongod
    state: restarted
  tags:
    - mongo

- name: Prepare remote user
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_pass }}"
    name: "{{ username }}"
    password: "{{ mysql_user_pass }}"
    state: present
    priv: "*.*:ALL"
    host: "{{ item }}"
  with_items:
    - localhost
    - "%"
  tags:
    - mysql

- name: Open mysql for remote connections
  become: true
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: "^bind-address"
    line: "bind-address\t= 0.0.0.0"
  tags:
    - mysql

- name: Restart MySQL service
  become: true
  service:
    name: mysql
    state: restarted
  tags:
    - mysql

- name: Open postgresql for remote connections
  become: true
  lineinfile:
    path: "/etc/postgresql/{{ psql_version }}/main/postgresql.conf"
    regexp: "^#listen_addresses"
    line: "listen_addresses = '*'"
  tags:
    - postgres

- name: Restart Postgres service
  become: true
  service:
    name: postgresql
    state: restarted
  tags:
    - postgres
