---
- name: Add PHP PPA Repository
  become: true
  apt_repository:
    repo: "ppa:ondrej/php"

- name: Install PHP Packages
  become: true
  apt:
    state: latest
    name:
      - "php{{ php_version }}-cli"
      - "php{{ php_version }}-curl"
      - "php{{ php_version }}-dev"
      - "php{{ php_version }}-fpm"
      - "php{{ php_version }}-gd"
      - "php{{ php_version }}-intl"
      - "php{{ php_version }}-ldap"
      - "php{{ php_version }}-mbstring"
      - "php{{ php_version }}-mysql"
      - "php{{ php_version }}-pgsql"
      - "php{{ php_version }}-sqlite3"
      - "php{{ php_version }}-xml"
      - "php{{ php_version }}-xmlrpc"
      - php-pear

- name: Install Pecl extensions
  become: true
  pear:
    name: "{{ item }}"
    state: present
  with_items:
    - pecl/xdebug
    - pecl/redis
    - pecl/oauth
    - pecl/mongodb
  tags:
    - pecl

- name: Prepare configuration file for XDebug
  become: true
  copy:
    dest: "/etc/php/{{ php_version }}/mods-available/xdebug.ini"
    content: |
      [xdebug]
      zend_extension="/usr/lib/php/{{ xdebug_date }}/xdebug.so"
      xdebug.remote_enable = 1
      xdebug.remote_autostart = 1
  tags:
    - pecl

- name: Enable XDebug config with symlink
  become: true
  file:
    state: link
    src: "/etc/php/{{ php_version }}/mods-available/xdebug.ini"
    dest: "/etc/php/{{ php_version }}/cli/conf.d/xdebug.ini"
  tags:
    - pecl

- name: Enable additional Pecl extensions
  become: true
  blockinfile:
    path: "/etc/php/{{ php_version }}/{{ item }}/php.ini"
    insertbefore: "; If you wish to have an extension loaded automatically"
    block: |
      extension=redis.so
      extension=oauth.so
      extension=mongodb.so
  with_items:
    - cli
    - fpm
  tags:
    - pecl
    - phpini