---
- name: Install DNF plugins to manage DNF repos
  become: true
  ansible.builtin.dnf:
    name:
      - dnf-plugins-core

- name: Add Docker repository
  become: true
  command: "dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo"

- name: Install Docker
  become: true
  ansible.builtin.dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

- name: Add current user to docker group
  become: true
  user:
    name: "{{ username }}"
    groups: docker
    append: yes

- name: Ensure docker service is started
  become: true
  systemd_service:
    state: started
    enabled: true
    name: docker
